global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-app'
    static_configs:
      - targets: ['app:8080']

  # (Opcional) si el collector expone /metrics (no por defecto)
  # - job_name: 'otel-collector'
  #   static_configs:
  #     - targets: ['otel-collector:8888']
